"""
advisor.py — Answers specific user questions using current indicators.

Verdict logic is deterministic (if/else) to keep tests reliable.
Dashboard answer text is generated by Claude (Haiku) when the API key is set;
falls back to hand-written text if the key is missing or the call fails.
Telegram answers always use the hand-written format for consistent structure.
"""

import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from src.predictor import Indicators


def _ask_claude(question: str, ind: Indicators, verdict: str) -> str | None:
    """Call Claude to generate a natural language dashboard answer.
    Returns None if the key is missing or the call fails (triggers fallback)."""
    try:
        import config
        if not config.ANTHROPIC_API_KEY or config.ANTHROPIC_API_KEY.startswith("your_"):
            return None
        import anthropic
        client = anthropic.Anthropic(api_key=config.ANTHROPIC_API_KEY)
        rsi_label = (
            "overbought" if ind.rsi_14 >= 70
            else "oversold" if ind.rsi_14 <= 30
            else "neutral"
        )
        prompt = f"""You are a personal financial advisor helping a US student decide when to \
send money to India (USD → INR via a remittance app).

Current market data:
- USD/INR rate: {ind.current_rate:.4f}
- Dynamic target: {ind.dynamic_target:.4f}  (48-hour moving average + 0.5)
- RSI (14): {ind.rsi_14:.1f} ({rsi_label})
- Trend: {ind.trend_label}  (slope {ind.trend_slope:+.5f}/hr)
- 24h forecast: {ind.predicted_24h:.4f}
- 48h forecast: {ind.predicted_48h:.4f}
- Model confidence (R²): {ind.confidence:.2f}

The analysis verdict is: {verdict.upper()}

Question the student asked: {question}

Write a 2-3 sentence personal, direct answer. Be conversational, not robotic. \
No bullet points. Lead with the recommendation, then give the reason backed by the data. \
Use the actual rate numbers. Keep it under 70 words."""

        message = client.messages.create(
            model=config.CLAUDE_MODEL,
            max_tokens=160,
            messages=[{"role": "user", "content": prompt}],
        )
        return message.content[0].text.strip()
    except Exception:
        return None


def send_in_one_hour(ind: Indicators) -> tuple[str, str, str]:
    """
    Should I send in the next hour?
    Returns (verdict, dashboard_answer, telegram_answer)
    """
    rate    = ind.current_rate
    target  = ind.dynamic_target
    rsi     = ind.rsi_14
    trend   = ind.trend_label
    pred_1h = round(ind.current_rate + (ind.predicted_24h - ind.current_rate) / 24, 4)

    # --- Verdict + fallback text ---
    if rate >= target:
        if rsi >= 70 or trend == "falling":
            verdict = "yes"
            fallback_answer = (
                f"**Yes — send within the hour.**\n\n"
                f"Rate is **{rate:.2f}** (above your target of {target:.2f}). "
                f"RSI is {rsi:.0f} and trend is {trend} — classic signs the rate is about to drop. "
                f"Waiting longer risks locking in a worse rate."
            )
            tg = (
                f"🟢 *Send within the hour.*\n\n"
                f"Rate is *{rate:.2f}* — above target {target:.2f}.\n"
                f"RSI {rsi:.0f} + {trend} trend = rate likely dropping soon.\n"
                f"_Don't wait._"
            )
        elif trend == "rising" and pred_1h > rate + 0.05:
            verdict = "maybe"
            fallback_answer = (
                f"**Maybe wait a little longer.**\n\n"
                f"Rate is **{rate:.2f}** (above target) and still rising — "
                f"could reach ~{pred_1h:.2f} in the next hour. "
                f"If you need certainty, sending now at {rate:.2f} is still a good rate. "
                f"If you can watch it, give it 30–60 more minutes."
            )
            tg = (
                f"🟡 *You could wait 30–60 minutes.*\n\n"
                f"Rate is *{rate:.2f}*, still rising toward ~{pred_1h:.2f}.\n"
                f"Sending now is fine — waiting could squeeze out a little more."
            )
        else:
            verdict = "yes"
            fallback_answer = (
                f"**Yes — go ahead.**\n\n"
                f"Rate is **{rate:.2f}**, above your target of {target:.2f}. "
                f"No strong signal to wait. Sending now is a solid call."
            )
            tg = (
                f"🟢 *Go ahead and send.*\n\n"
                f"Rate is *{rate:.2f}* — above target {target:.2f}.\n"
                f"No strong reason to wait."
            )
    else:
        gap     = round(target - rate, 2)
        verdict = "no"
        fallback_answer = (
            f"**No — don't send yet.**\n\n"
            f"Rate is **{rate:.2f}**, which is {gap} below your target of {target:.2f}. "
            f"Sending now means you're leaving money on the table. "
            f"Predicted rate in an hour: ~{pred_1h:.2f}."
        )
        tg = (
            f"🔴 *Don't send yet.*\n\n"
            f"Rate is *{rate:.2f}* — {gap} below target {target:.2f}.\n"
            f"Wait for a better window."
        )

    question = "Should I send money in the next hour?"
    claude_answer = _ask_claude(question, ind, verdict)
    answer = claude_answer if claude_answer else fallback_answer

    return verdict, answer, tg


def send_tomorrow(ind: Indicators) -> tuple[str, str, str]:
    """
    Should I send tomorrow?
    Returns (verdict, dashboard_answer, telegram_answer)
    """
    rate   = ind.current_rate
    target = ind.dynamic_target
    pred24 = ind.predicted_24h
    pred48 = ind.predicted_48h
    trend  = ind.trend_label

    if rate >= target and pred24 < rate - 0.10:
        verdict = "now"
        fallback_answer = (
            f"**Send today, not tomorrow.**\n\n"
            f"Rate is **{rate:.2f}** now — above your target of {target:.2f}. "
            f"But forecast drops to {pred24:.2f} in 24 hours. "
            f"Tomorrow will likely be worse. Lock in today's rate."
        )
        tg = (
            f"🟢 *Send today, not tomorrow.*\n\n"
            f"Rate is *{rate:.2f}* now but forecast drops to {pred24:.2f} in 24h.\n"
            f"Don't wait — today is better."
        )
    elif pred24 >= target and pred24 > rate + 0.05:
        verdict = "wait"
        fallback_answer = (
            f"**Tomorrow looks better — consider waiting.**\n\n"
            f"Rate is {rate:.2f} today, but forecast shows **{pred24:.2f}** in 24 hours — "
            f"above your target of {target:.2f} and higher than today. "
            f"If you can wait, tomorrow may get you a better deal. "
            f"Keep alerts on in case the rate moves early."
        )
        tg = (
            f"🟡 *Consider waiting until tomorrow.*\n\n"
            f"Today: *{rate:.2f}* | Tomorrow forecast: *{pred24:.2f}*\n"
            f"Target: {target:.2f} — tomorrow looks slightly better."
        )
    elif pred24 >= target:
        verdict = "maybe"
        fallback_answer = (
            f"**Tomorrow could work — but today is also fine.**\n\n"
            f"Forecast shows {pred24:.2f} in 24h, which is above your target of {target:.2f}. "
            f"Current rate is {rate:.2f}. "
            f"If rate is above target today, send today. If not, tomorrow looks promising."
        )
        tg = (
            f"🟡 *Tomorrow could work.*\n\n"
            f"Forecast: *{pred24:.2f}* in 24h — above target {target:.2f}.\n"
            f"Watch the rate today and decide."
        )
    else:
        verdict = "no"
        fallback_answer = (
            f"**Tomorrow doesn't look great either.**\n\n"
            f"Forecast shows {pred24:.2f} in 24h and {pred48:.2f} in 48h — "
            f"both below your target of {target:.2f}. "
            f"The market isn't cooperating right now. Keep monitoring and wait for a better window."
        )
        tg = (
            f"🔴 *Tomorrow doesn't look great.*\n\n"
            f"Forecast 24h: *{pred24:.2f}* | 48h: *{pred48:.2f}*\n"
            f"Both below target {target:.2f}. Keep monitoring."
        )

    question = "Should I send money tomorrow, or is today better?"
    claude_answer = _ask_claude(question, ind, verdict)
    answer = claude_answer if claude_answer else fallback_answer

    return verdict, answer, tg


def best_time_to_send(ind: Indicators) -> tuple[str, str, str]:
    """
    When is the best time to send?
    Returns (verdict, dashboard_answer, telegram_answer)
    """
    rate   = ind.current_rate
    target = ind.dynamic_target
    rsi    = ind.rsi_14
    trend  = ind.trend_label
    pred24 = ind.predicted_24h
    pred48 = ind.predicted_48h

    if rate >= target and (rsi >= 65 or trend == "falling"):
        verdict = "yes"
        fallback_answer = (
            f"**Right now is the best window.**\n\n"
            f"Rate is **{rate:.2f}** — above your target of {target:.2f}. "
            f"RSI is {rsi:.0f} and trend is {trend}, which means the rate has likely peaked "
            f"and is due for a pullback. This is the window. Send now."
        )
        tg = (
            f"🟢 *Best time: Right now.*\n\n"
            f"Rate *{rate:.2f}* is above target {target:.2f}.\n"
            f"RSI {rsi:.0f} + {trend} trend = peak conditions.\n"
            f"_Send now before it drops._"
        )
    elif rate >= target and trend == "rising" and pred24 > rate:
        verdict = "maybe"
        fallback_answer = (
            f"**Now is good, but the next 12–24 hours could be even better.**\n\n"
            f"Rate is **{rate:.2f}** (above target) and still rising toward a forecast of {pred24:.2f}. "
            f"Watch for RSI to cross 70 — that's your ideal trigger to send. "
            f"Set an alert and check back in a few hours."
        )
        tg = (
            f"🟡 *Good now, potentially better in 12–24h.*\n\n"
            f"Rate *{rate:.2f}* → forecast *{pred24:.2f}* in 24h.\n"
            f"Watch for RSI > 70 as the ideal send trigger."
        )
    elif pred24 >= target:
        verdict = "wait"
        fallback_answer = (
            f"**Best window: within the next 24 hours.**\n\n"
            f"Current rate is {rate:.2f} — not quite at target yet. "
            f"But forecast shows **{pred24:.2f}** in 24 hours, which is above your target of {target:.2f}. "
            f"Be ready to send tomorrow. Keep alerts on."
        )
        tg = (
            f"🟡 *Best window: next 24 hours.*\n\n"
            f"Current: *{rate:.2f}* | Forecast 24h: *{pred24:.2f}*\n"
            f"Target {target:.2f} — be ready tomorrow."
        )
    elif pred48 >= target:
        verdict = "wait"
        fallback_answer = (
            f"**Best window: next 24–48 hours.**\n\n"
            f"Rate is {rate:.2f} now, below target. "
            f"Forecast shows {pred48:.2f} in 48 hours — above your target of {target:.2f}. "
            f"Hold off for now. Your alert will fire when the rate hits the window."
        )
        tg = (
            f"🟡 *Best window: 24–48 hours out.*\n\n"
            f"Forecast 48h: *{pred48:.2f}* — above target {target:.2f}.\n"
            f"Hold off. Alert will fire when the time comes."
        )
    else:
        verdict = "no"
        fallback_answer = (
            f"**No clear window in the next 48 hours.**\n\n"
            f"Rate is {rate:.2f}, target is {target:.2f}. "
            f"Forecast stays at {pred24:.2f} (24h) and {pred48:.2f} (48h) — both below target. "
            f"The market isn't at a favorable point right now. "
            f"Keep the scheduler running — it'll alert you the moment conditions improve."
        )
        tg = (
            f"🔴 *No clear window in the next 48h.*\n\n"
            f"Rate *{rate:.2f}* | Target {target:.2f}\n"
            f"Forecast: {pred24:.2f} (24h) · {pred48:.2f} (48h)\n"
            f"Keep monitoring — alert fires when conditions improve."
        )

    question = "When is the best time to send money? Should I send now or wait?"
    claude_answer = _ask_claude(question, ind, verdict)
    answer = claude_answer if claude_answer else fallback_answer

    return verdict, answer, tg
